aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: test
    accessKeySecret: test
    bucketName: macro-oss
    policy:
      expire: 300
    maxSize: 10
    callback: http://106.53.106.41:8080/aliyun/oss/callback
    dir:
      prefix: mall/images/
spring:
  datasource:
    url: jdbc:mysql://106.53.132.192:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Mall@2026_root
  data:
    redis:
      host: 106.53.132.192
      database: 0
      port: 6379
      password: Mall@2026_redis
minio:
  endpoint: http://106.53.106.41:9000
  bucketName: mall
  accessKey: minioadmin
  secretKey: minioadmin
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.macro.mall: info
logstash:
  host: 8.134.65.121
